# Once [PR 102](https://github.com/jshimko/meteor-launchpad/pull/102) is complete, restore thsi to shimko
#FROM jshimko/meteor-launchpad:latest
FROM quay.io/mrwinstead/meteor-launchpad:101-add-wait-for-it
